url: https://townbee.github.io

# Site settings
title: Townbee
# email: townbee@muenchen.enactus.de
email: nicola.miskowiec@gmail.com
description: "Wir bringen seit 2017 motivierten Flüchtlingen mit verschiedensten Hintergründen das Imkern bei. Dabei leisten wir ein Beitrag gegen das Bienensterben."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Townbee.Enactus
  - title: github
    url: http://github.com/townbee

collections:
    members:

# Build settings
markdown: kramdown
permalink: pretty
